import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

base_dir = Path(__file__).resolve().parents[2]
data_path = base_dir / 'data' / 'raw' / 'retail_sales.csv'

# Load dataset
sales = pd.read_csv(data_path)
sales['order_date'] = pd.to_datetime(sales['order_date'])

# Create a working summary table
summary = sales.groupby(['region', 'category'], as_index=False)['revenue'].sum()
summary = summary.sort_values('revenue', ascending=False)

# Compute metrics for communication
segment_summary = sales.groupby('customer_segment', as_index=False)['revenue'].sum().sort_values('revenue', ascending=False)
channel_summary = sales.groupby('channel', as_index=False)['revenue'].sum().sort_values('revenue', ascending=False)

print('Kaggle-style Retail Analysis')
print('=' * 60)
print('Top region/category combinations by revenue:')
print(summary.head(10).to_string(index=False))
print('\nRevenue by customer segment:')
print(segment_summary.to_string(index=False))
print('\nRevenue by channel:')
print(channel_summary.to_string(index=False))

# Visualize
plt.figure(figsize=(10, 6))
sns.barplot(data=summary.head(10), x='revenue', y='region', hue='category', dodge=False)
plt.title('Top Region and Category Revenue Mix')
plt.tight_layout()
plt.savefig(base_dir / 'images' / 'kaggle_region_category.png', dpi=150)
plt.close()

print('\nSaved visualization to:', base_dir / 'images' / 'kaggle_region_category.png')
print('\nBusiness takeaway: the strongest revenue is generated by a small number of region/category combinations, so resource allocation should be targeted to those clusters.')
